- include: prereq-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
      - rbenv
      - redhat

- include: prereq-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
      - rbenv
      - debian

- name: clone rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest={{ ANSIBLE_RBENV_RBENV_USER_HOME }}/.rbenv accept_hostkey=yes 
  sudo_user: "{{ ANSIBLE_RBENV_RBENV_USER }}"
  tags:
      - rbenv

- name: clone ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{ ANSIBLE_RBENV_RBENV_USER_HOME }}/.rbenv/plugins/ruby-build accept_hostkey=yes
  sudo_user: "{{ ANSIBLE_RBENV_RBENV_USER }}"


- name: create environ dir
  file: path={{ ANSIBLE_RBENV_RBENV_USER_HOME }}/profile.d state=directory mode=0755
  sudo_user: "{{ ANSIBLE_RBENV_RBENV_USER }}"
  tags:
      - rbenv

- name: add environ scrip
  copy: src=../files/rbenv.sh dest={{ ANSIBLE_RBENV_RBENV_USER_HOME }}/profile.d/ mode=0755
  sudo_user: "{{ ANSIBLE_RBENV_RBENV_USER }}"
  tags:
      - rbenv

- name: check bash
  shell: "[ -x $(which bash) ] && echo 'Found' || echo ''"
  register: executable_bash
  changed_when: false 
  tags:
      - rbenv

- name: add bash environ
  include: bash-env.yml
  when: executable_bash.stdout
  tags:
      - rbenv

- name: check zsh
  shell: "[ -x $(which zsh) ] && echo 'Found' || echo ''"
  register: executable_zsh
  changed_when: false 
  tags:
      - rbenv

- name: add zsh environ
  include: zsh-env.yml
  when: executable_zsh.stdout
  tags:
      - rbenv

- name: ruby install
  shell: "echo y | {{ ANSIBLE_RBENV_RBENV_USER_HOME }}/.rbenv/bin/rbenv install {{ ANSIBLE_RBENV_RUBY_VERSION }}"
  sudo_user: "{{ ANSIBLE_RBENV_RBENV_USER }}"
  changed_when: false 
  tags:
      - rbenv
      - ruby install
  
- name: ruby global 
  shell: "'{{ ANSIBLE_RBENV_RBENV_USER_HOME }}'/.rbenv/bin/rbenv global {{ ANSIBLE_RBENV_RUBY_VERSION }}"
  sudo_user: "{{ ANSIBLE_RBENV_RBENV_USER }}"
  changed_when: false 
  tags:
      - rbenv
      - ruby global

- name: ruby version check
  shell: "su - root -c 'ruby --version 2>&1 | grep -F \"{{ ANSIBLE_RBENV_RUBY_VERSION }}\"'" 
  changed_when: false
  tags:
      - rbenv
      - ruby check 
