- name: apt キャッシュアップデート
  apt: update_cache=yes

- name: Install prereq パッケージ
  apt: pkg="{{ item }}" state=present
  with_items:
    - git
    - curl

- name: Install developmentパッケージ
  apt: pkg="{{ item }}" state=present
  with_items:
    - libc-ares2
    - libev4
    - libv8-3.8.9.20
