- name: .zshenv存在チェック
  stat: path={{ ANSIBLE_RBENV_RBENV_USER_HOME }}/.zshenv
  register: is_file
  sudo_user: "{{ ANSIBLE_RBENV_RBENV_USER }}"
  changed_when: false 
  always_run: yes

- name: .zshenv作成
  file: path={{ ANSIBLE_RBENV_RBENV_USER_HOME }}/.zshenv state=touch owner={{ ANSIBLE_RBENV_RBENV_USER }}  mode=0755
  sudo_user: "{{ ANSIBLE_RBENV_RBENV_USER }}"
  when: is_file.stat.md5 is not defined

- name: .zshenv_permission設定
  file: path={{ ANSIBLE_RBENV_RBENV_USER_HOME }}/.zshenv state=file owner={{ ANSIBLE_RBENV_RBENV_USER }}  mode=0755
  sudo_user: "{{ ANSIBLE_RBENV_RBENV_USER }}"
  when: is_file.stat.md5 is defined

- name: .zshenvでprofile.d/rbenv.shを読み込むように変更
  lineinfile: line='source {{ ANSIBLE_RBENV_RBENV_USER_HOME }}/profile.d/rbenv.sh' dest={{ ANSIBLE_RBENV_RBENV_USER_HOME }}/.zshenv insertafter=EOF
  sudo_user: "{{ ANSIBLE_RBENV_RBENV_USER }}"

